package com.qqspace.dao;

import com.qqspace.bean.Admin;
import org.springframework.stereotype.Component;

@Component
public interface AdminMapper {

    int deleteByPrimaryKey(Integer id);

    int insert(Admin record);


    int insertSelective(Admin record);


    Admin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     */
    int updateByPrimaryKey(Admin record);

    /*根据账号密码判断是否为管理员登录*/
    Admin selectByNameAndPassword(Admin record);
}