package com.qqspace.dao;

import java.util.List;

import com.qqspace.vo.EChartsVO;
import org.apache.ibatis.annotations.Param;

import com.qqspace.bean.Article;


public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_info
     *
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_info
     *
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_info
     *
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_info
     *
     */
    Article selectByPrimaryKey(Integer articleId);
    /**
   	 * 根据标签id查询所有文章
   	 * @param articleLabelid
   	 * @return List<ArticleModel>
   	 */
   	List<Article> selectByLabelid(Integer articleLabelid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_info
     *
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_info
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_info
     *
     */
    int updateByPrimaryKey(Article record);
    /**
     *  根据articleId且articleUserid，查询文章
     * @param articleId
     * @param articleUserid
     * @return Article
     */
	Article selectByAidAndUid(@Param("articleId")Integer articleId,@Param("articleUserid") Integer articleUserid);
	/**
	 * 根据用户id 查询它关注的人文章权限为为博友的文章，所有公开的文章，个人所有文章的总数
	 * @param userid
	 * @return int
	 */
	int selectByArticleCount(Integer userid);
	/**
	 * 根据登录用户id 查询它关注的人文章权限为为博友的文章，所有公开的文章，个人所有文章,有分页
	 * @param userid
	 * @return List<Article>
	 */
	List<Article> selectByArticleUserid(@Param("userid")Integer userid,@Param("begin") Integer begin,@Param("recordSize") Integer recordSize);
	/**
	 * 根据用户id 查询个人所有文章,有分页
	 * @param userid
	 * @param labelId 
	 * @return List<Article>
	 */
	List<Article> selectAllByUserid(@Param("userid")Integer userid,@Param("labelId")Integer labelId, @Param("begin") Integer begin,@Param("recordSize") Integer recordSize);
	/**
	 * 根据用户id 查询个人所有文章的总数
	 * @param userid
	 * @param labelId 
	 * @return int
	 */
	int selectAllCountByUserid(@Param("userid")Integer userid, @Param("labelId") Integer labelId);
	/**
	 *  根据登录用户id 查询它关注的人文章权限为为博友的文章，所有公开的文章，个人所有文章，浏览量最高前12记录
	 * @param articleUserid
	 * @return List<Article>
	 */
	List<Article> selectArticleTOPTwelveByUserId(Integer articleUserid);

	/**
	 * 根据审核状态查询文章
	 * @return
	 */
	Integer selectArticlesCountByAccessright(@Param("articleAccessright") Integer articleAccessright);

    List<EChartsVO> selectMonthArticlesByAccessRight(@Param("articleAccessright")Integer accessRight);

	/**
	 * 根据条件查询文章数量
	 * @param userId
	 * @param articleTitle
	 * @param articleAuthor
	 * @param accessRight
	 * @return
	 */
    int selectAllCountByCondition(@Param("userId") Integer userId,
								  @Param("articleTitle") String articleTitle,
								  @Param("articleAuthor") String articleAuthor,
								  @Param("articleAccessright") Integer accessRight);

	List<Article> selectAllByCondition(
			@Param("offset")Integer offset,
			@Param("size")Integer size,
			@Param("userId")Integer userId,
			@Param("articleTitle")String articleTitle,
			@Param("articleAuthor")String articleAuthor,
			@Param("articleAccessright")Integer accessRight);
}