package com.qqspace.dao;

import java.util.List;

import com.qqspace.bean.CommentBack;

public interface CommentBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentback_info
     *
     */
    int deleteByPrimaryKey(Integer cbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentback_info
     *
     */
    int insert(CommentBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentback_info
     *
     */
    int insertSelective(CommentBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentback_info
     *
     */
    CommentBack selectByPrimaryKey(Integer cbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentback_info
     *
     */
    int updateByPrimaryKeySelective(CommentBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentback_info
     *
     */
    int updateByPrimaryKeyWithBLOBs(CommentBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentback_info
     *
     */
    int updateByPrimaryKey(CommentBack record);
    /**
     *  根据评论id 查询回复信息
     * @param cbCommentid
     * @return List<CommentBack>
     */
	List<CommentBack> selectByCbCommentid(Integer cbCommentid);
	/**
	 * 根据评论id 删除评论信息
	 * @param cbCommentid
	 */
	void deleteBycbCommentid(Integer cbCommentid);

    Integer selectAllCommentBackCount();
}