package com.qqspace.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.qqspace.bean.Follow;

public interface FollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_info
     *
    
     */
    int deleteByPrimaryKey(Integer foId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_info
     *
     */
    int insert(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_info
     *
     */
    int insertSelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_info
     *
     */
    Follow selectByPrimaryKey(Integer foId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_info
     *
     */
    int updateByPrimaryKeySelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_info
     */
    int updateByPrimaryKey(Follow record);
    /**
     *根据 关注人id 和被关注人id  查询关注信息
     * @param foUserid 关注人id
     * @param foBeuserid 被关注人id
     * @return Follow
     */
	Follow selectByUserIdAndBeUserId(@Param("foUserid")Integer foUserid, @Param("foBeuserid")Integer foBeuserid);
	/**
	 *  根据关注人id 和被关注人id 删除关注
	 * @param foUserid 关注人id
	 * @param foBeuserid  被关注人id
	 * @return  int
	 */
	int delByUseridAndBeUserid(@Param("foUserid")Integer foUserid,@Param("foBeuserid")Integer foBeuserid);
	/**
	 *  根据关注人id 查询 查询它关注信息总数
	 * @param foUserid
	 * @return int
	 */ 
	int selectCountByFoUserid(Integer foUserid);
	/**
	 * 根据关注人id 查询 查询它关注信息
	 * @param foUserid 关注人id
	 * @param begin 分页参数:从哪开始
	 * @param recordSize 分页参数:偏移量为多少
	 * @return List<Follow>
	 */
	List<Follow> selectByFoUserid(@Param("foUserid")Integer foUserid,@Param("begin") Integer begin,@Param("recordSize") Integer recordSize);
	/**
	 * 根据用户id 查询关注量和粉丝量
	 * @param userid 用户id
	 * @return Follow
	 */
	Follow selectFansandFollowCountByUserid(Integer userid);
}