package com.qqspace.dao;

import java.util.List;

import com.qqspace.vo.EChartsVO;
import org.apache.ibatis.annotations.Param;

import com.qqspace.bean.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     */
    User selectByPrimaryKey(Integer id);
    
    User selectByuserLogin(String userLogin);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     */
    int updateByPrimaryKey(User record);
    /**
     * 根据userid更改用户主题
     * @param user
     * @return int
     */
	int updateByUserTheme(User user);
	/**
	 * 根据userid更改用户留言寄语
	 * @param userSendWord
	 * @param id
	 * @return int
	 */
	int updateSendWordByUserid(@Param("userSendWord")String userSendWord,@Param("id") Integer id);

	int selectAllUsersCount();

    /**
     * 查询近一周的用户新增数量
     * @return
     */
	List<EChartsVO> selectWeekAddUserCount();

    /**
     * 按条件查询用户总数
     * @param condition
     * @return
     */
    Integer selectAllUsersCountWithPageByCondition(@Param("condition")User condition);

    /**
     * 按条件查询用户列表
     * @param offset 偏移量
     * @param size 查询数量
     * @param condition 条件
     * @return Lisst<User>
     */
    List<User> selectAllUsersWithPageByCondition(@Param("offset")Integer offset,@Param("size") Integer size,@Param("condition") User condition);
}