package com.qqspace.dao;

import com.qqspace.bean.UserRecentlyLogin;

public interface UserRecentlyLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     */
    int insert(UserRecentlyLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     */
    int insertSelective(UserRecentlyLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     */
    UserRecentlyLogin selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     */
    int updateByPrimaryKeySelective(UserRecentlyLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     */
    int updateByPrimaryKey(UserRecentlyLogin record);
}