package com.qqspace.dao;

import com.qqspace.bean.UserPhoto;

public interface UserPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     */
    int insert(UserPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     */
    int insertSelective(UserPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     */
    UserPhoto selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     */
    int updateByPrimaryKeySelective(UserPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     */
    int updateByPrimaryKey(UserPhoto record);
}