package com.qqspace.bean;

public class AdminPhoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_photo.admin_id
     *
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_photo.admin_photoImg
     *
     */
    private String adminPhotoimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_photo.admin_id
     *
     * @return the value of admin_photo.admin_id
     *
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_photo.admin_id
     *
     * @param adminId the value for admin_photo.admin_id
     *
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_photo.admin_photoImg
     *
     * @return the value of admin_photo.admin_photoImg
     *
     */
    public String getAdminPhotoimg() {
        return adminPhotoimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_photo.admin_photoImg
     *
     * @param adminPhotoimg the value for admin_photo.admin_photoImg
     *
     */
    public void setAdminPhotoimg(String adminPhotoimg) {
        this.adminPhotoimg = adminPhotoimg == null ? null : adminPhotoimg.trim();
    }
}