package com.qqspace.bean;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_Id
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_title
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_image
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private String articleImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_intro
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private String articleIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_author
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private String articleAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_accessRight
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private Integer articleAccessright;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_push
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private Integer articlePush;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_examine
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private Integer articleExamine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_labelId
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private Integer articleLabelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_userId
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private Integer articleUserid;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_createDate
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private Date articleCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.article_content
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    private String articleContent;

    
    //所属的标签名称
  	private String articleLabeName;
    
  	//浏览量
  	private Integer hiCount;

  	
	public Integer getHiCount() {
		return hiCount;
	}

	public void setHiCount(Integer hiCount) {
		this.hiCount = hiCount;
	}

	public String getArticleLabeName() {
		return articleLabeName;
	}

	public void setArticleLabeName(String articleLabeName) {
		this.articleLabeName = articleLabeName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_Id
     *
     * @return the value of article_info.article_Id
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_Id
     *
     * @param articleId the value for article_info.article_Id
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_title
     *
     * @return the value of article_info.article_title
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_title
     *
     * @param articleTitle the value for article_info.article_title
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_image
     *
     * @return the value of article_info.article_image
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public String getArticleImage() {
        return articleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_image
     *
     * @param articleImage the value for article_info.article_image
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleImage(String articleImage) {
        this.articleImage = articleImage == null ? null : articleImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_intro
     *
     * @return the value of article_info.article_intro
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public String getArticleIntro() {
        return articleIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_intro
     *
     * @param articleIntro the value for article_info.article_intro
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleIntro(String articleIntro) {
        this.articleIntro = articleIntro == null ? null : articleIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_author
     *
     * @return the value of article_info.article_author
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public String getArticleAuthor() {
        return articleAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_author
     *
     * @param articleAuthor the value for article_info.article_author
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor == null ? null : articleAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_accessRight
     *
     * @return the value of article_info.article_accessRight
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public Integer getArticleAccessright() {
        return articleAccessright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_accessRight
     *
     * @param articleAccessright the value for article_info.article_accessRight
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleAccessright(Integer articleAccessright) {
        this.articleAccessright = articleAccessright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_push
     *
     * @return the value of article_info.article_push
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public Integer getArticlePush() {
        return articlePush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_push
     *
     * @param articlePush the value for article_info.article_push
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticlePush(Integer articlePush) {
        this.articlePush = articlePush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_examine
     *
     * @return the value of article_info.article_examine
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public Integer getArticleExamine() {
        return articleExamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_examine
     *
     * @param articleExamine the value for article_info.article_examine
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleExamine(Integer articleExamine) {
        this.articleExamine = articleExamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_labelId
     *
     * @return the value of article_info.article_labelId
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public Integer getArticleLabelid() {
        return articleLabelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_labelId
     *
     * @param articleLabelid the value for article_info.article_labelId
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleLabelid(Integer articleLabelid) {
        this.articleLabelid = articleLabelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_userId
     *
     * @return the value of article_info.article_userId
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public Integer getArticleUserid() {
        return articleUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_userId
     *
     * @param articleUserid the value for article_info.article_userId
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleUserid(Integer articleUserid) {
        this.articleUserid = articleUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_createDate
     *
     * @return the value of article_info.article_createDate
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public Date getArticleCreatedate() {
        return articleCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_createDate
     *
     * @param articleCreatedate the value for article_info.article_createDate
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleCreatedate(Date articleCreatedate) {
        this.articleCreatedate = articleCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.article_content
     *
     * @return the value of article_info.article_content
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.article_content
     *
     * @param articleContent the value for article_info.article_content
     *
     * @mbg.generated Wed Jul 17 13:36:21 CST 2021
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }
}