package com.qqspace.bean;

import java.util.Date;

public class CommentLikeCount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentlikecount_info.cl_id
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    private Integer clId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentlikecount_info.cl_commentId
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    private Integer clCommentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentlikecount_info.cl_dianzanid
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    private Integer clDianzanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentlikecount_info.cl_date
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    private Date clDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentlikecount_info.cl_id
     *
     * @return the value of commentlikecount_info.cl_id
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    public Integer getClId() {
        return clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentlikecount_info.cl_id
     *
     * @param clId the value for commentlikecount_info.cl_id
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    public void setClId(Integer clId) {
        this.clId = clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentlikecount_info.cl_commentId
     *
     * @return the value of commentlikecount_info.cl_commentId
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    public Integer getClCommentid() {
        return clCommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentlikecount_info.cl_commentId
     *
     * @param clCommentid the value for commentlikecount_info.cl_commentId
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    public void setClCommentid(Integer clCommentid) {
        this.clCommentid = clCommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentlikecount_info.cl_dianzanid
     *
     * @return the value of commentlikecount_info.cl_dianzanid
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    public Integer getClDianzanid() {
        return clDianzanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentlikecount_info.cl_dianzanid
     *
     * @param clDianzanid the value for commentlikecount_info.cl_dianzanid
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    public void setClDianzanid(Integer clDianzanid) {
        this.clDianzanid = clDianzanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentlikecount_info.cl_date
     *
     * @return the value of commentlikecount_info.cl_date
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    public Date getClDate() {
        return clDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentlikecount_info.cl_date
     *
     * @param clDate the value for commentlikecount_info.cl_date
     *
     * @mbg.generated Wed Jul 31 09:57:32 CST 2021
     */
    public void setClDate(Date clDate) {
        this.clDate = clDate;
    }
}