package com.qqspace.bean;

import java.util.Date;

public class Follow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_info.fo_id
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    private Integer foId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_info.fo_note
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    private String foNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_info.fo_userid
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    private Integer foUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_info.fo_beUserid
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    private Integer foBeuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_info.fo_createDate
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    private Date foCreatedate;
    //粉丝(被多少人关注)
  	private Integer fans;
  	//关注了多少人
  	private Integer followCount;
  	
  	
    public Integer getFans() {
		return fans;
	}

	public void setFans(Integer fans) {
		this.fans = fans;
	}

	public Integer getFollowCount() {
		return followCount;
	}

	public void setFollowCount(Integer followCount) {
		this.followCount = followCount;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_info.fo_id
     *
     * @return the value of follow_info.fo_id
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public Integer getFoId() {
        return foId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_info.fo_id
     *
     * @param foId the value for follow_info.fo_id
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public void setFoId(Integer foId) {
        this.foId = foId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_info.fo_note
     *
     * @return the value of follow_info.fo_note
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public String getFoNote() {
        return foNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_info.fo_note
     *
     * @param foNote the value for follow_info.fo_note
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public void setFoNote(String foNote) {
        this.foNote = foNote == null ? null : foNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_info.fo_userid
     *
     * @return the value of follow_info.fo_userid
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public Integer getFoUserid() {
        return foUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_info.fo_userid
     *
     * @param foUserid the value for follow_info.fo_userid
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public void setFoUserid(Integer foUserid) {
        this.foUserid = foUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_info.fo_beUserid
     *
     * @return the value of follow_info.fo_beUserid
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public Integer getFoBeuserid() {
        return foBeuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_info.fo_beUserid
     *
     * @param foBeuserid the value for follow_info.fo_beUserid
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public void setFoBeuserid(Integer foBeuserid) {
        this.foBeuserid = foBeuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_info.fo_createDate
     *
     * @return the value of follow_info.fo_createDate
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public Date getFoCreatedate() {
        return foCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_info.fo_createDate
     *
     * @param foCreatedate the value for follow_info.fo_createDate
     *
     * @mbg.generated Fri Jul 26 12:56:41 CST 2021
     */
    public void setFoCreatedate(Date foCreatedate) {
        this.foCreatedate = foCreatedate;
    }
}