package com.qqspace.bean;

public class HitsCount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hitscount_info.hi_articleId
     *
     * @mbg.generated Fri Jul 26 12:48:29 CST 2021
     */
    private Integer hiArticleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hitscount_info.hi_count
     *
     * @mbg.generated Fri Jul 26 12:48:29 CST 2021
     */
    private Integer hiCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hitscount_info.hi_articleId
     *
     * @return the value of hitscount_info.hi_articleId
     *
     * @mbg.generated Fri Jul 26 12:48:29 CST 2021
     */
    public Integer getHiArticleid() {
        return hiArticleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hitscount_info.hi_articleId
     *
     * @param hiArticleid the value for hitscount_info.hi_articleId
     *
     * @mbg.generated Fri Jul 26 12:48:29 CST 2021
     */
    public void setHiArticleid(Integer hiArticleid) {
        this.hiArticleid = hiArticleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hitscount_info.hi_count
     *
     * @return the value of hitscount_info.hi_count
     *
     * @mbg.generated Fri Jul 26 12:48:29 CST 2021
     */
    public Integer getHiCount() {
        return hiCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hitscount_info.hi_count
     *
     * @param hiCount the value for hitscount_info.hi_count
     *
     * @mbg.generated Fri Jul 26 12:48:29 CST 2021
     */
    public void setHiCount(Integer hiCount) {
        this.hiCount = hiCount;
    }
}