package com.qqspace.bean;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.me_id
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    private Integer meId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.me_leaveId
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    private Integer meLeaveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.me_userId
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    private Integer meUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.me_date
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    private Date meDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.me_content
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    private String meContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.me_id
     *
     * @return the value of message_info.me_id
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    
    private String meLeaveName;
    
    
    public String getMeLeaveName() {
		return meLeaveName;
	}

	public void setMeLeaveName(String meLeaveName) {
		this.meLeaveName = meLeaveName;
	}

	public Integer getMeId() {
        return meId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.me_id
     *
     * @param meId the value for message_info.me_id
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    public void setMeId(Integer meId) {
        this.meId = meId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.me_leaveId
     *
     * @return the value of message_info.me_leaveId
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    public Integer getMeLeaveid() {
        return meLeaveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.me_leaveId
     *
     * @param meLeaveid the value for message_info.me_leaveId
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    public void setMeLeaveid(Integer meLeaveid) {
        this.meLeaveid = meLeaveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.me_userId
     *
     * @return the value of message_info.me_userId
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    public Integer getMeUserid() {
        return meUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.me_userId
     *
     * @param meUserid the value for message_info.me_userId
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    public void setMeUserid(Integer meUserid) {
        this.meUserid = meUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.me_date
     *
     * @return the value of message_info.me_date
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    public Date getMeDate() {
        return meDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.me_date
     *
     * @param meDate the value for message_info.me_date
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    public void setMeDate(Date meDate) {
        this.meDate = meDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.me_content
     *
     * @return the value of message_info.me_content
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    public String getMeContent() {
        return meContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.me_content
     *
     * @param meContent the value for message_info.me_content
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    public void setMeContent(String meContent) {
        this.meContent = meContent == null ? null : meContent.trim();
    }
}