package com.qqspace.bean;

import java.util.Date;

public class PhotoAlbums {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photoalbums_info.pa_id
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    private Integer paId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photoalbums_info.pa_name
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    private String paName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photoalbums_info.pa_coverImg
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    private String paCoverimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photoalbums_info.pa_createDate
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    private Date paCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photoalbums_info.pa_description
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    private String paDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photoalbums_info.pa_jurisdiction
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    private Integer paJurisdiction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photoalbums_info.pa_userId
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    private Integer paUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photoalbums_info.pa_id
     *
     * @return the value of photoalbums_info.pa_id
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public Integer getPaId() {
        return paId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photoalbums_info.pa_id
     *
     * @param paId the value for photoalbums_info.pa_id
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public void setPaId(Integer paId) {
        this.paId = paId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photoalbums_info.pa_name
     *
     * @return the value of photoalbums_info.pa_name
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public String getPaName() {
        return paName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photoalbums_info.pa_name
     *
     * @param paName the value for photoalbums_info.pa_name
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public void setPaName(String paName) {
        this.paName = paName == null ? null : paName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photoalbums_info.pa_coverImg
     *
     * @return the value of photoalbums_info.pa_coverImg
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public String getPaCoverimg() {
        return paCoverimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photoalbums_info.pa_coverImg
     *
     * @param paCoverimg the value for photoalbums_info.pa_coverImg
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public void setPaCoverimg(String paCoverimg) {
        this.paCoverimg = paCoverimg == null ? null : paCoverimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photoalbums_info.pa_createDate
     *
     * @return the value of photoalbums_info.pa_createDate
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public Date getPaCreatedate() {
        return paCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photoalbums_info.pa_createDate
     *
     * @param paCreatedate the value for photoalbums_info.pa_createDate
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public void setPaCreatedate(Date paCreatedate) {
        this.paCreatedate = paCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photoalbums_info.pa_description
     *
     * @return the value of photoalbums_info.pa_description
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public String getPaDescription() {
        return paDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photoalbums_info.pa_description
     *
     * @param paDescription the value for photoalbums_info.pa_description
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public void setPaDescription(String paDescription) {
        this.paDescription = paDescription == null ? null : paDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photoalbums_info.pa_jurisdiction
     *
     * @return the value of photoalbums_info.pa_jurisdiction
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public Integer getPaJurisdiction() {
        return paJurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photoalbums_info.pa_jurisdiction
     *
     * @param paJurisdiction the value for photoalbums_info.pa_jurisdiction
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public void setPaJurisdiction(Integer paJurisdiction) {
        this.paJurisdiction = paJurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photoalbums_info.pa_userId
     *
     * @return the value of photoalbums_info.pa_userId
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public Integer getPaUserid() {
        return paUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photoalbums_info.pa_userId
     *
     * @param paUserid the value for photoalbums_info.pa_userId
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    public void setPaUserid(Integer paUserid) {
        this.paUserid = paUserid;
    }
}