package com.qqspace.bean;

public class UserPhoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.user_id
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    private Integer userId;

	//用户头像图片名称
	private String userPhotoName;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.user_photoImg
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    private String userPhotoimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.user_id
     *
     * @return the value of user_photo.user_id
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.user_id
     *
     * @param userId the value for user_photo.user_id
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.user_photoImg
     *
     * @return the value of user_photo.user_photoImg
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    
    public String getUserPhotoimg() {
        return userPhotoimg;
    }

    public String getUserPhotoName() {
		return userPhotoName;
	}

	public void setUserPhotoName(String userPhotoName) {
		this.userPhotoName = userPhotoName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.user_photoImg
     *
     * @param userPhotoimg the value for user_photo.user_photoImg
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    public void setUserPhotoimg(String userPhotoimg) {
        this.userPhotoimg = userPhotoimg == null ? null : userPhotoimg.trim();
    }
}