package com.qqspace.bean;

import java.util.Date;

public class UserRecentlyLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recentlylogin.user_id
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recentlylogin.user_loginTime
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    private Date userLogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recentlylogin.user_loginIP
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    private String userLoginip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recentlylogin.user_id
     *
     * @return the value of user_recentlylogin.user_id
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recentlylogin.user_id
     *
     * @param userId the value for user_recentlylogin.user_id
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recentlylogin.user_loginTime
     *
     * @return the value of user_recentlylogin.user_loginTime
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    public Date getUserLogintime() {
        return userLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recentlylogin.user_loginTime
     *
     * @param userLogintime the value for user_recentlylogin.user_loginTime
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    public void setUserLogintime(Date userLogintime) {
        this.userLogintime = userLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recentlylogin.user_loginIP
     *
     * @return the value of user_recentlylogin.user_loginIP
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    public String getUserLoginip() {
        return userLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recentlylogin.user_loginIP
     *
     * @param userLoginip the value for user_recentlylogin.user_loginIP
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    public void setUserLoginip(String userLoginip) {
        this.userLoginip = userLoginip == null ? null : userLoginip.trim();
    }
}